version: '3.8'

services:
  fleet-master:
    build: .
    container_name: chronoroot-fleet-master
    network_mode: "host"             
    volumes: 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - .:/app
      - fleet_db_volume:/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  fleet_db_volume:
    name: chronoroot_fleet_data